package tic_tac_toe;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.lang.*;
import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
    /**
 *
 * @author LENOVO
 */
public class TicTacToe extends javax.swing.JFrame {
    
    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField1.setEnabled(false);

        jTextField2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField2.setEnabled(false);

        jTextField3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField3.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField3.setEnabled(false);

        jTextField4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField4.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField4.setEnabled(false);

        jTextField5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField5.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField5.setEnabled(false);

        jTextField6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField6.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField6.setEnabled(false);

        jTextField7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField7.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField7.setEnabled(false);

        jTextField8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField8.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField8.setEnabled(false);

        jTextField9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField9.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jTextField9.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel3.setText("3");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel4.setText("4");

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel5.setText("5");

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel6.setText("6");

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel7.setText("7");

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel8.setText("8");

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jLabel9.setText("9");

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jButton1.setText("Player 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField10.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N

        jTextField11.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jButton2.setText("Player 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 18)); // NOI18N
        jButton3.setText("RE-PLAY");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("STOP");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(49, 49, 49)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextField10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton3)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jButton1)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
int Input1=Integer.parseInt(jTextField10.getText());
if (Input1<1 || Input1>9)
JOptionPane.showMessageDialog(this,"Enter a Valid Position (1..9)");
else
{
if ((Input1==1 && jTextField1.getText().isEmpty()) ||
(Input1==2 && jTextField2.getText().isEmpty()) ||
(Input1==3 && jTextField3.getText().isEmpty()) ||
(Input1==4 && jTextField4.getText().isEmpty()) ||
(Input1==5 && jTextField5.getText().isEmpty()) ||
(Input1==6 && jTextField6.getText().isEmpty()) ||
(Input1==7 && jTextField7.getText().isEmpty()) ||
(Input1==8 && jTextField8.getText().isEmpty()) ||
(Input1==9 && jTextField9.getText().isEmpty())
)
{
switch (Input1)
{
case 1:jTextField1.setText("X");break;
case 2:jTextField2.setText("X");break;
case 3:jTextField3.setText("X");break;
case 4:jTextField4.setText("X");break;
case 5:jTextField5.setText("X");break;
case 6:jTextField6.setText("X");break;
case 7:jTextField7.setText("X");break;
case 8:jTextField8.setText("X");break;
case 9:jTextField9.setText("X");break;
}
if ((jTextField1.getText().equals("X") &&
jTextField2.getText().equals("X") &&
jTextField3.getText().equals("X"))||
(jTextField4.getText().equals("X") &&
jTextField5.getText().equals("X") &&
jTextField6.getText().equals("X"))||
(jTextField7.getText().equals("X") &&
jTextField8.getText().equals("X") &&
jTextField9.getText().equals("X"))||
(jTextField1.getText().equals("X") &&
jTextField4.getText().equals("X") &&
jTextField7.getText().equals("X"))||
(jTextField2.getText().equals("X") &&
jTextField5.getText().equals("X") &&
jTextField8.getText().equals("X"))||
(jTextField3.getText().equals("X") &&
jTextField6.getText().equals("X") &&
jTextField9.getText().equals("X"))||
(jTextField1.getText().equals("X") &&
jTextField5.getText().equals("X") &&
jTextField9.getText().equals("X"))||
(jTextField3.getText().equals("X") &&
jTextField5.getText().equals("X") &&
        jTextField7.getText().equals("X"))
){
        int id=0;
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ttt", "root", "mysql");
        Statement stmt=(Statement)con.createStatement();
        
        String query="select ID from game order by ID DESC LIMIT 0,1;";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next()){
         id=rs.getInt("ID");
        }
        
        String qry="update game set Winner='"+jButton1.getText()+"' where ID= "+id+"; ";
   stmt.executeUpdate(qry);
JOptionPane.showMessageDialog(this,""+jButton1.getText()+" Wins");    
    }
    catch(Exception e)
    {
     JOptionPane.showMessageDialog(this,e.getMessage());
    }

}else
if (!jTextField1.getText().isEmpty() &&
!jTextField2.getText().isEmpty() &&
!jTextField3.getText().isEmpty() &&
!jTextField4.getText().isEmpty() &&
!jTextField5.getText().isEmpty() &&
!jTextField6.getText().isEmpty() &&
!jTextField7.getText().isEmpty() &&
!jTextField8.getText().isEmpty() &&
!jTextField9.getText().isEmpty())
JOptionPane.showMessageDialog(this,"It is a DRAW...");
else
jTextField11.setEditable(true);
jButton1.setEnabled(false);
jButton2.setEnabled(true);
jTextField10.setEditable(false);
}
else
JOptionPane.showMessageDialog
(this,"Already Occupied Option RE-ENTER (1..9)");
}
jTextField10.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
int Input2=Integer.parseInt(jTextField11.getText());
if (Input2<1 || Input2>9)
JOptionPane.showMessageDialog
(this,"Enter a Valid Position (1..9)");
else
{
if ((Input2==1 && jTextField1.getText().isEmpty()) ||
(Input2==2 && jTextField2.getText().isEmpty()) ||
(Input2==3 && jTextField3.getText().isEmpty()) ||
(Input2==4 && jTextField4.getText().isEmpty()) ||
(Input2==5 && jTextField5.getText().isEmpty()) ||
(Input2==6 && jTextField6.getText().isEmpty()) ||
(Input2==7 && jTextField7.getText().isEmpty()) ||
(Input2==8 && jTextField8.getText().isEmpty()) ||
        (Input2==9 && jTextField9.getText().isEmpty())
)
{
switch (Input2)
{
case 1:jTextField1.setText("O");break;
case 2:jTextField2.setText("O");break;
case 3:jTextField3.setText("O");break;
case 4:jTextField4.setText("O");break;
case 5:jTextField5.setText("O");break;
case 6:jTextField6.setText("O");break;
case 7:jTextField7.setText("O");break;
case 8:jTextField8.setText("O");break;
case 9:jTextField9.setText("O");break;
}
if ((jTextField1.getText().equals("O") &&
jTextField2.getText().equals("O") &&
jTextField3.getText().equals("O"))||
(jTextField4.getText().equals("O") &&
jTextField5.getText().equals("O") &&
jTextField6.getText().equals("O"))||
(jTextField7.getText().equals("O") &&
jTextField8.getText().equals("O") &&
jTextField9.getText().equals("O"))||
(jTextField1.getText().equals("O") &&
jTextField4.getText().equals("O") &&
jTextField7.getText().equals("O"))||
        (jTextField2.getText().equals("O") &&
jTextField5.getText().equals("O") &&
jTextField8.getText().equals("O"))||
(jTextField3.getText().equals("O") &&
jTextField6.getText().equals("O") &&
jTextField9.getText().equals("O"))||
(jTextField1.getText().equals("O") &&
jTextField5.getText().equals("O") &&
jTextField9.getText().equals("O"))||
(jTextField3.getText().equals("O") &&
jTextField5.getText().equals("O") &&
jTextField7.getText().equals("O"))
){
    int id=0;
try
    {
        Class.forName("java.sql.DriverManager");
        Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ttt", "root", "mysql");
        Statement stmt=(Statement)con.createStatement();
        
        String query="select ID from game order by ID DESC LIMIT 0,1;";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next()){
         id=rs.getInt("ID");
        }
        
        String qry="update game set Winner='"+jButton2.getText()+"' where ID= "+id+"; ";
   stmt.executeUpdate(qry);
JOptionPane.showMessageDialog(this,""+jButton2.getText()+" Wins");
    
    }
    catch(Exception e)
    {
     JOptionPane.showMessageDialog(this,e.getMessage());
    }

}
else
if (!jTextField1.getText().isEmpty() &&
!jTextField2.getText().isEmpty() &&
!jTextField3.getText().isEmpty() &&
!jTextField4.getText().isEmpty() &&
!jTextField5.getText().isEmpty() &&
!jTextField6.getText().isEmpty() &&
!jTextField7.getText().isEmpty() &&
!jTextField8.getText().isEmpty() &&
!jTextField9.getText().isEmpty()
)
JOptionPane.showMessageDialog(this,"It is a DRAW...");
else
jTextField10.setEditable(true);
jButton2.setEnabled(false);
jButton1.setEnabled(true);
jTextField11.setEditable(false);
}
else
JOptionPane.showMessageDialog
(this,"Already Occupied Option RE-ENTER (1..9)");
}
jTextField11.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 // TODO add your handling code here:
        jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
jTextField9.setText("");
jTextField10.setEditable(true);
jTextField11.setEditable(false);
jButton1.setEnabled(true);
jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed
public void my_update(String str1,String str2) {
		jButton1.setText(str1);
                jButton2.setText(str2);
                jButton2.setEnabled(false);
                jTextField11.setEditable(false);
	}
    /**
     * @param args the command line arguments
     */
public static void main(String args[]){
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new TicTacToe().setVisible(true);
                 
           }
        });
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
} 
